-- Role: "CryptoUser1"
-- DROP ROLE IF EXISTS "CryptoUser1";
CREATE ROLE "CryptoUser1" WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:xrJiEnxLWvct4lKzlkLTlg==$wgaI9Bd1g+Cr//SsMJEwkRlO2yAInreGaHLFt1ANU5E=:MhrSTUTNTlhkCSN6MpwGYHZ5oAb6EWzGY8X0gsreQGQ=';
  
  
  -- Database: Crypto

-- DROP DATABASE IF EXISTS "Crypto";

CREATE DATABASE "Crypto"
    WITH
    OWNER = "CryptoUser1"
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
GRANT ALL ON DATABASE "Crypto" TO "CryptoUser1";
GRANT TEMPORARY, CONNECT ON DATABASE "Crypto" TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "CryptoUser1";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "CryptoUser1";